name: Deploy Media Server

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/ubuntu/SERVER1/Media-server

            git pull origin main

            cd backend/hybrid-file-server
            npm install
            pm2 restart hybrid-api

            cd ../../frontend
            npm install
            npm run build

            sudo systemctl restart nginx